# Generated by Django 5.1.6 on 2025-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
