# Generated by Django 5.1.6 on 2025-02-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0002_armor_level_weapon_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='armor',
            name='body_part',
        ),
    ]
