# Generated by Django 5.1.6 on 2025-02-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0006_treasure_armor_price_armor_sell_coeff_weapon_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('max_health', models.IntegerField(default=100)),
                ('money', models.IntegerField(default=0)),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FighterClub.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='FighterEquipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('armor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FighterClub.armor')),
                ('body_part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.bodypart')),
                ('fighter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.fighter')),
            ],
            options={
                'unique_together': {('fighter_id', 'body_part_name')},
            },
        ),
    ]
