# Generated by Django 5.1.6 on 2025-02-25 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0007_fighter_fighterequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FighterClub.weapon'),
        ),
    ]
