# Generated by Django 5.1.6 on 2025-02-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0009_rename_body_part_name_fighterequipment_body_part_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighterequipment',
            old_name='armor_id',
            new_name='armor',
        ),
        migrations.AddField(
            model_name='fighter',
            name='inventory_armor',
            field=models.ManyToManyField(blank=True, to='FighterClub.armor'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='inventory_treasures',
            field=models.ManyToManyField(blank=True, to='FighterClub.treasure'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='inventory_weapons',
            field=models.ManyToManyField(blank=True, to='FighterClub.weapon'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipped_weapon', to='FighterClub.weapon'),
        ),
    ]
