# Generated by Django 5.1.6 on 2025-02-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0010_rename_armor_id_fighterequipment_armor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('max_hp', models.IntegerField(default=100)),
                ('damage', models.IntegerField(default=1)),
                ('inventory_armor', models.ManyToManyField(blank=True, to='FighterClub.armor')),
                ('inventory_treasures', models.ManyToManyField(blank=True, to='FighterClub.treasure')),
                ('inventory_weapons', models.ManyToManyField(blank=True, to='FighterClub.weapon')),
            ],
        ),
    ]
