# Generated by Django 5.1.6 on 2025-02-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0011_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='fighter_state',
            field=models.IntegerField(default=0),
        ),
    ]
