# Generated by Django 5.1.6 on 2025-02-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0012_fighter_fighter_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='fighter_state',
            field=models.CharField(default='INVENTORY', max_length=63),
        ),
    ]
