# Generated by Django 5.1.6 on 2025-03-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0014_fighter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='inventory_armor',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='inventory_treasures',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='inventory_weapons',
        ),
    ]
