# Generated by Django 5.1.6 on 2025-03-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0015_remove_fighter_inventory_armor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryArmor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.armor')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.fighter')),
            ],
        ),
        migrations.AddField(
            model_name='fighter',
            name='inventory_armor',
            field=models.ManyToManyField(blank=True, through='FighterClub.InventoryArmor', to='FighterClub.armor'),
        ),
        migrations.CreateModel(
            name='InventoryTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.fighter')),
                ('treasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.treasure')),
            ],
        ),
        migrations.AddField(
            model_name='fighter',
            name='inventory_treasures',
            field=models.ManyToManyField(blank=True, through='FighterClub.InventoryTreasure', to='FighterClub.treasure'),
        ),
        migrations.CreateModel(
            name='InventoryWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.fighter')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='fighter',
            name='inventory_weapons',
            field=models.ManyToManyField(blank=True, through='FighterClub.InventoryWeapon', to='FighterClub.weapon'),
        ),
    ]
