# Generated by Django 5.1.6 on 2025-03-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0016_inventoryarmor_fighter_inventory_armor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='inventory_armor',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='inventory_treasures',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='inventory_weapons',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='inventory_armor',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='inventory_treasures',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='inventory_weapons',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryarmor',
            unique_together={('fighter', 'armor')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorytreasure',
            unique_together={('fighter', 'treasure')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryweapon',
            unique_together={('fighter', 'weapon')},
        ),
    ]
