# Generated by Django 5.1.6 on 2025-03-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0017_remove_fighter_inventory_armor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighterequipment',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FighterClub.armor'),
        ),
    ]
