# Generated by Django 5.1.6 on 2025-03-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0018_alter_fighterequipment_armor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='fighter_state',
        ),
    ]
