# Generated by Django 5.1.6 on 2025-03-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0020_fighterstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FighterState',
        ),
    ]
