# Generated by Django 5.1.6 on 2025-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0021_delete_fighterstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterState',
            fields=[
                ('name', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('entry_point', models.CharField(default='/', max_length=63)),
            ],
        ),
    ]
