# Generated by Django 5.1.6 on 2025-03-17 06:53

from django.db import migrations


def create_states(apps, schema_editor):
    state = apps.get_model('FighterClub', 'FighterState')
    state.objects.create(name='Инвентарь', entry_point='/inventory')
    state.objects.create(name='Магазин', entry_point='/shop')
    state.objects.create(name='Выбор задания', entry_point='/mission_selection')
    state.objects.create(name='Бой', entry_point='/fight')
    state.objects.create(name='Сбор лута', entry_point='/loot_collection')
    state.objects.create(name='Экипировка', entry_point='/equipment')


class Migration(migrations.Migration):
    dependencies = [
        ('FighterClub', '0022_fighterstate'),
    ]

    operations = [
        migrations.RunPython(create_states),
    ]
