# Generated by Django 5.1.6 on 2025-03-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0025_remove_fighterstate_entry_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='level',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='level',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='level',
        ),
    ]
