# Generated by Django 5.1.6 on 2025-03-19 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0026_remove_armor_level_remove_fighter_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('treasureGenerator', models.CharField(max_length=255)),
                ('treasureVolume', models.IntegerField()),
                ('monsters', models.ManyToManyField(to='FighterClub.monster')),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FighterClub.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.stage')),
            ],
        ),
    ]
