# Generated by Django 5.1.6 on 2025-03-19 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0027_stage_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='monsters',
        ),
        migrations.CreateModel(
            name='StageMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.monster')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.stage')),
            ],
            options={
                'unique_together': {('stage', 'monster')},
            },
        ),
    ]
