# Generated by Django 5.1.6 on 2025-03-19 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0028_remove_stage_monsters_stagemonster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FighterClub.stage'),
        ),
    ]
