# Generated by Django 5.1.6 on 2025-03-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0029_alter_stage_next'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.fighter', unique=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.stage')),
            ],
        ),
        migrations.CreateModel(
            name='FightMonster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hp', models.IntegerField(default=0)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.fight')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.monster')),
            ],
        ),
    ]
