# Generated by Django 5.1.6 on 2025-03-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0030_fight_fightmonster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightmonster',
            name='fight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.fight'),
        ),
    ]
