# Generated by Django 5.1.6 on 2025-03-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0031_alter_fightmonster_fight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='fighter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.fighter'),
        ),
        migrations.AlterField(
            model_name='fightmonster',
            name='fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.fight'),
        ),
    ]
