# Generated by Django 5.1.6 on 2025-03-25 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0032_alter_fight_fighter_alter_fightmonster_fight'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterArmor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('armor', models.IntegerField(default=0)),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.bodypart')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.monster')),
            ],
            options={
                'unique_together': {('monster', 'body_part')},
            },
        ),
    ]
