# Generated by Django 5.1.6 on 2025-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0033_monsterarmor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryarmor',
            old_name='armor',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='inventorytreasure',
            old_name='treasure',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='inventoryweapon',
            old_name='weapon',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='treasure',
            name='sell_coeff',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryarmor',
            unique_together={('fighter', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorytreasure',
            unique_together={('fighter', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryweapon',
            unique_together={('fighter', 'item')},
        ),
    ]
