# Generated by Django 5.1.6 on 2025-04-28 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0034_rename_armor_inventoryarmor_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotionEffect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('sell_coeff', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.potioneffect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryPotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.fighter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FighterClub.potion')),
            ],
            options={
                'unique_together': {('fighter', 'item')},
            },
        ),
    ]
