# Generated by Django 5.1.6 on 2025-04-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FighterClub', '0035_potioneffect_potion_inventorypotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
